### ISSUE TITLE
can you give me some input data?

### ISSUE THREAD

**Issue by huangqianhong** [sdyinzhen/MH-Dir#2]
Hi,I am interested in your repos about uncertainty quantify. Thank you very much for open-source the project.But I can't run this project.Can you give me some input data?

**Comment by sdyinzhen** [comment]
Hi Qianhong, 

Sorry, we cannot share the original data as we don't have permission. I will replace it with some synthetic data and let you know once ready (hopefully this month). 

There is another solution. If you can upload and share a similar dataset, I can show you how to run the code. Cheers, David

**Comment by huangqianhong** [comment]
Hi David,
Thank you for your sincere reply.on the one hand,I am very much looking forward to your synthetic dataset.
On the other hand,I try to run this project with our dataset which no permission to upload.Cheers,QianHong
